import { ChatRoom } from '../models/room.model';

export const MOCK_ROOMS: ChatRoom[] = [
  {
    id: 'general',
    name: 'General',
    description: 'Company-wide announcements and chit-chat',
    memberCount: 24,
    onlineCount: 8,
    unreadCount: 0,
    lastMessage: 'Welcome to ChatFlow!',
    lastMessageAt: new Date(),
  },
  {
    id: 'angular',
    name: 'Angular',
    description: 'Everything Angular',
    memberCount: 18,
    onlineCount: 5,
    unreadCount: 4,
    lastMessage: 'Signals make this so much cleaner',
    lastMessageAt: new Date(),
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'Types, generics, and tooling',
    memberCount: 15,
    onlineCount: 3,
    unreadCount: 0,
    lastMessage: 'Strict mode saved me again',
    lastMessageAt: new Date(),
  },
  {
    id: 'rxjs',
    name: 'RxJS',
    description: 'Streams, operators, marble diagrams',
    memberCount: 12,
    onlineCount: 4,
    unreadCount: 2,
    lastMessage: 'switchMap cancelled the old request',
    lastMessageAt: new Date(),
  },
  {
    id: 'development',
    name: 'Development',
    description: 'General engineering discussion',
    memberCount: 20,
    onlineCount: 6,
    unreadCount: 7,
    lastMessage: 'PR is up for review',
    lastMessageAt: new Date(),
  },
  {
    id: 'random',
    name: 'Random',
    description: 'Off-topic chatter',
    memberCount: 22,
    onlineCount: 9,
    unreadCount: 0,
    lastMessage: 'Anyone up for coffee?',
    lastMessageAt: new Date(),
  },
];
